global:
  scrape_interval: 15s

scrape_configs:

  # this job is just to illustrate that everything works
  # the docker-compose file also runs node-exporter.
  # The section below tells prometheus to scrape that intance
  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]

  # Here you need to define your own (local) service
  - job_name: "my-local-service"
    scrape_interval: 1s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:8080"]
